# Generated by Django 4.2.1 on 2023-06-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="delivery",
            name="unique_delivery_order",
        ),
    ]
