# Generated by Django 4.2.1 on 2023-06-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_completed",
        ),
        migrations.AddField(
            model_name="book",
            name="is_buy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
