# Generated by Django 4.2.1 on 2023-06-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0004_remove_book_is_buy_order_is_buy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_buy",
        ),
    ]
