# Generated by Django 4.2.1 on 2023-06-05 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0005_remove_order_is_buy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=100)),
                ("courier", models.CharField(max_length=100)),
                ("delivery_date", models.DateField()),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_app.order",
                    ),
                ),
            ],
        ),
    ]
