# Generated by Django 4.2.1 on 2023-06-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0005_alter_delivery_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="is_delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="is_delivered",
            field=models.BooleanField(default=False),
        ),
    ]
